backend:
  name: github
  repo: evolutions-urbaines/evolutions-urbaines

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: landing
    label: Landing Pages
    folder: src/pages/landing
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title · Segment Name }
      - { name: segmentAroundExpression, label: Segment "around" expression }
      - { name: segmentLogoUrl, label: Segment Logo URL }
      - { name: drivyAddressSearchUrl, label: Drivy address search URL }
