backend:
  name: github
  repo: evolutions-urbaines/evolutions-urbaines

media_folder: static/assets
public_folder: assets

display_url: https://evolutions-urbaines.fr

collections:
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: landing-business
    label: Landing Pages 路 Business
    folder: src/pages/landing
    create: true
    filter: { field: segmentCategory, value: business }
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title 路 Segment Name }
      - { name: segmentCategory, label: Segment Category, widget: select, options: [business, leisure]}
      - { name: segmentAroundExpression, label: Segment "around" expression }
      - { name: segmentLogoUrl, label: Segment Logo URL, required: false }
      - { name: drivyAddressSearchUrl, label: Drivy address search URL }
      - { name: segmentDrivyReferralUrl, label: Segment Drivy referral URL, required: false }
      - { name: segmentRecommendation, label: Segment recommendation, widget: boolean }
      - { name: segmentBackgroundUrl, label: Segment background URL, required: false }
      - { name: segmentRepresentativePhotoUrl, label: Segment Representative photo URL, required: false }
      - { name: segmentRepresentativeName, label: Segment Representative name, required: false }
      - { name: segmentRepresentativeRole, label: Segment Representative role, required: false }
      - { name: segmentRepresentativeSpeech, label: Segment Representative speech, widget: text, required: false }
  - name: landing-leisure
    label: Landing Pages 路 Leisure
    folder: src/pages/landing
    create: true
    filter: { field: segmentCategory, value: leisure }
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title 路 Segment Name }
      - { name: segmentCategory, label: Segment Category, widget: select, options: [business, leisure]}
      - { name: segmentAroundExpression, label: Segment "around" expression }
      - { name: segmentLogoUrl, label: Segment Logo URL, required: false }
      - { name: drivyAddressSearchUrl, label: Drivy address search URL }
      - { name: segmentDrivyReferralUrl, label: Segment Drivy referral URL, required: false }
      - { name: segmentRecommendation, label: Segment recommendation, widget: boolean }
      - { name: segmentBackgroundUrl, label: Segment background URL, required: false }
      - { name: segmentRepresentativePhotoUrl, label: Segment Representative photo URL, required: false }
      - { name: segmentRepresentativeName, label: Segment Representative name, required: false }
      - { name: segmentRepresentativeRole, label: Segment Representative role, required: false }
      - { name: segmentRepresentativeSpeech, label: Segment Representative speech, widget: text, required: false }
