backend:
  name: github
  repo: evolutions-urbaines/evolutions-urbaines

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
